_base_: sparse_view_lego_n8_dav2s.yaml

experiment:
  name: blender_lego_n8_ssl_mv_dav2s_pearson

ssl:
  depth_consist:
    enabled: true
    weight: 1.0
    mode: pearson
    pearson_weight: 0.05
    pearson_target_transform: identity
    start_iter: 500
    alpha_thresh: 0.5
    space: disparity
    depth_eps: 0.001

  pseudo_view:
    enabled: false
    weight: 0.0
    start_sample_pseudo: 2000
    end_sample_pseudo: 6650
    sample_pseudo_interval: 1
