"""Generate per-scene configs for the Blender avg-8 @ n=8 sweep.

Mirrors ``configs/sparse_view_lego_n8.yaml`` and
``configs/sparse_view_lego_n8_dav2s.yaml`` for the remaining 7 scenes.
Output -> ``configs/_blender_n8/blender_<scene>_n8_{baseline,dav2s}.yaml``.

Run once::

    python scripts/_gen_blender_n8_configs.py

(Idempotent; rewrites every time so it's safe to re-run.)
"""
from __future__ import annotations

from pathlib import Path

_ROOT = Path(__file__).resolve().parents[1]
_OUT = _ROOT / "configs" / "_blender_n8"
_DATA_ROOT_WIN = "data/nerf_synthetic"

_SCENES = ["chair", "drums", "ficus", "hotdog", "materials", "mic", "ship"]

_BASELINE_TEMPLATE = """\
_base_: ../base.yaml

# Blender avg-8 sweep, scene = {scene}, n=8 baseline.
# Auto-generated by scripts/_gen_blender_n8_configs.py — do not edit by hand.

experiment:
  name: blender_{scene}_n8

data:
  type: nerf_synthetic
  root: {data_root}
  scene: {scene}
  n_train_views: 8
  train_view_ids: null
  image_downsample: 1
  white_background: true

model:
  sh_degree: 3
  init:
    type: random_in_box
    num_points: 100000
    extent: 1.5
    rgb_init: 0.5
  scale_init_factor: 0.01

renderer:
  near_plane: 0.01
  far_plane: 1.0e10
  rasterize_mode: antialiased
  packed: false
  absgrad: true
  render_mode: RGB+ED

strategy:
  type: default
  prune_opa: 0.005
  grow_grad2d: 0.0002
  grow_scale3d: 0.01
  prune_scale3d: 0.1
  refine_start_iter: 500
  refine_stop_iter: 15000
  refine_every: 100
  reset_every: 3000
  absgrad: true
  revised_opacity: false
  verbose: false

train:
  iterations: 7000
  ssim_lambda: 0.2

ssl:
  multiview_photo: {{enabled: false, weight: 0.0}}
  depth_consist:   {{enabled: false, weight: 0.0}}
  ema_teacher:     {{enabled: false, weight: 0.0}}
  pseudo_view:     {{enabled: false, weight: 0.0}}
  feature:         {{enabled: false, weight: 0.0}}

eval:
  render_test_at_end: true
  num_test_renders: 200
  lpips: true
  lpips_net: vgg
"""

_DAV2S_TEMPLATE = """\
_base_: ../base.yaml

# Blender avg-8 sweep, scene = {scene}, n=8 + DAv2-Small + multiview_photo.
# Auto-generated by scripts/_gen_blender_n8_configs.py — do not edit by hand.

experiment:
  name: blender_{scene}_n8_ssl_mv_dav2s

data:
  type: nerf_synthetic
  root: {data_root}
  scene: {scene}
  n_train_views: 8
  train_view_ids: null
  image_downsample: 1
  white_background: true
  depth_prior:
    enabled: true
    backend: cache
    tag: depth_anything_v2_small
    kind: disparity
    required: false

model:
  sh_degree: 3
  init:
    type: random_in_box
    num_points: 100000
    extent: 1.5
    rgb_init: 0.5
  scale_init_factor: 0.01

renderer:
  near_plane: 0.01
  far_plane: 1.0e10
  rasterize_mode: antialiased
  packed: false
  absgrad: true
  render_mode: RGB+ED

strategy:
  type: default
  prune_opa: 0.005
  grow_grad2d: 0.0002
  grow_scale3d: 0.01
  prune_scale3d: 0.1
  refine_start_iter: 500
  refine_stop_iter: 15000
  refine_every: 100
  reset_every: 3000
  absgrad: true
  revised_opacity: false
  verbose: false

train:
  iterations: 7000
  ssim_lambda: 0.2

ssl:
  multiview_photo:
    enabled: true
    weight: 0.10
    start_iter: 1500
    n_neighbors: 1
    alpha_thresh: 0.5
    ssim_lambda: 0.0
    depth_eps: 0.001
    occlusion_check: true
    occlusion_start_iter: 3000
    occlusion_tau: 0.10
    occlusion_alpha_thresh: 0.30

  depth_consist:
    enabled: true
    weight: 0.05
    start_iter: 500
    alpha_thresh: 0.5
    space: disparity
    depth_eps: 0.001

  ema_teacher:     {{enabled: false, weight: 0.0}}
  pseudo_view:     {{enabled: false, weight: 0.0}}
  feature:         {{enabled: false, weight: 0.0}}

eval:
  render_test_at_end: true
  num_test_renders: 200
  lpips: true
  lpips_net: vgg
"""


def main() -> None:
    _OUT.mkdir(parents=True, exist_ok=True)
    for s in _SCENES:
        b = _OUT / f"blender_{s}_n8_baseline.yaml"
        d = _OUT / f"blender_{s}_n8_dav2s.yaml"
        b.write_text(_BASELINE_TEMPLATE.format(scene=s, data_root=_DATA_ROOT_WIN),
                     encoding="utf-8")
        d.write_text(_DAV2S_TEMPLATE.format(scene=s, data_root=_DATA_ROOT_WIN),
                     encoding="utf-8")
        print(f"  wrote {b.name} + {d.name}")
    print(f"[done] {len(_SCENES)} scenes x 2 variants -> {_OUT}")


if __name__ == "__main__":
    main()
