"""Compare ship ablation (A0/A1/A2/A3/A4) and v8_hard against v7 baseline.

Reads metrics.json from outputs/{run_name}/, prints a Markdown table to
stdout *and* writes outputs/_ablation_summary.md.

Layout:
    | run | tag | PSNR | SSIM | LPIPS | #G | ΔPSNR vs v7 |

Usage:
    python scripts/ablation_compare.py
    python scripts/ablation_compare.py --root outputs
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

# (run_name, tag, baseline_run_name_for_delta)
SHIP_ABLATION = [
    ("blender_ship_n8_w3_aggrprune_long_v7_widerpseudo_x45k", "A0 v7 baseline", None),
    ("ablation_ship_A1_rand_bg",                              "A1 +rand_bg",     "blender_ship_n8_w3_aggrprune_long_v7_widerpseudo_x45k"),
    ("ablation_ship_A2_conservative_prune",                   "A2 +cons_prune",  "blender_ship_n8_w3_aggrprune_long_v7_widerpseudo_x45k"),
    ("ablation_ship_A3_weak_pvd",                             "A3 +weak_pvd",    "blender_ship_n8_w3_aggrprune_long_v7_widerpseudo_x45k"),
    ("blender_ship_n8_v8_hard_x45k",                          "A4 v8_hard full", "blender_ship_n8_w3_aggrprune_long_v7_widerpseudo_x45k"),
]

V8_HARD = [
    ("blender_ship_n8_v8_hard_x45k",      "ship  v8_hard",      "blender_ship_n8_w3_aggrprune_long_v7_widerpseudo_x45k"),
    ("blender_materials_n8_v8_hard_x45k", "materials v8_hard",  "blender_materials_n8_w3_aggrprune_long_v7_widerpseudo_x45k"),
    ("blender_drums_n8_v8_hard_x45k",     "drums v8_hard",      "blender_drums_n8_w3_aggrprune_long_v7_widerpseudo_x45k"),
]


def _load_metrics(run_dir: Path) -> Optional[Dict[str, Any]]:
    """Pick the metrics file with largest test coverage (same logic as collect_metrics)."""
    candidates: List[Tuple[int, int, Dict[str, Any]]] = []
    for prio, name in [(0, "metrics.json"), (1, "metrics_full.json")]:
        p = run_dir / name
        if not p.exists():
            continue
        try:
            with open(p, "r", encoding="utf-8") as f:
                payload = json.load(f)
            n_used = int(payload.get("num_test_views_used", 0) or 0)
            candidates.append((n_used, prio, payload))
        except Exception as e:
            print(f"[warn] failed to parse {p}: {e}")
    if not candidates:
        return None
    candidates.sort(key=lambda t: (t[0], t[1]))
    return candidates[-1][2]


def _fmt(v, fmt: str = "{:.4f}") -> str:
    return fmt.format(v) if v is not None else "—"


def _row(run_name: str, tag: str, baseline_psnr: Optional[float], root: Path) -> Tuple[str, Optional[float]]:
    run_dir = root / run_name
    payload = _load_metrics(run_dir) if run_dir.exists() else None
    if payload is None:
        line = f"| `{run_name}` | {tag} | — | — | — | — | (not found) |"
        return line, None
    m = payload.get("metrics", {})
    psnr = m.get("test/psnr")
    ssim = m.get("test/ssim")
    lpips = m.get("test/lpips")
    ng = payload.get("num_gaussians")
    if baseline_psnr is not None and psnr is not None:
        delta = psnr - baseline_psnr
        delta_s = f"{delta:+.3f}"
    else:
        delta_s = "—"
    ng_s = f"{ng:,}" if ng is not None else "—"
    line = (f"| `{run_name}` | {tag} | {_fmt(psnr)} | {_fmt(ssim)} | "
            f"{_fmt(lpips)} | {ng_s} | {delta_s} |")
    return line, psnr


def _emit_table(title: str, items, root: Path, lines: List[str]) -> None:
    lines.append(f"## {title}")
    lines.append("")
    lines.append("| run | tag | PSNR ↑ | SSIM ↑ | LPIPS ↓ | #G | ΔPSNR |")
    lines.append("|---|---|---:|---:|---:|---:|---:|")
    base_cache: Dict[str, Optional[float]] = {}
    for (run_name, tag, base_name) in items:
        if base_name is not None and base_name not in base_cache:
            base_payload = _load_metrics(root / base_name) if (root / base_name).exists() else None
            base_cache[base_name] = (base_payload or {}).get("metrics", {}).get("test/psnr")
        base_psnr = base_cache.get(base_name) if base_name else None
        row, _ = _row(run_name, tag, base_psnr, root)
        lines.append(row)
    lines.append("")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", type=str, default="outputs")
    args = ap.parse_args()

    root = Path(args.root)
    if not root.is_absolute():
        root = Path(__file__).resolve().parent.parent / root

    lines: List[str] = []
    lines.append("# Ablation / v8_hard comparison")
    lines.append("")
    lines.append("Auto-generated by `scripts/ablation_compare.py`. ΔPSNR is vs the"
                 " corresponding v7 x45k run.")
    lines.append("")

    _emit_table("Ship ablation (A0…A4)",   SHIP_ABLATION, root, lines)
    _emit_table("v8_hard on hard scenes",  V8_HARD,       root, lines)

    out_path = root / "_ablation_summary.md"
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"[ablation_compare] wrote {out_path}")
    print()
    for line in lines:
        print(line)


if __name__ == "__main__":
    main()
