"""Run the LLFF-8-scene sparse-view (N=3) sweep, baseline + DAv2.

For each scene in the canonical LLFF benchmark we run two experiments:

  1. ``{scene}_n3_baseline``  — pure 3DGS, no SSL (sanity / Δ reference).
  2. ``{scene}_n3_dav2s``     — 3DGS + multiview_photo + depth_consist
                               (Depth-Anything-V2-Small prior).

The configs mirror ``configs/llff_fern_n3_{baseline,dav2s}.yaml`` so the
results are directly comparable.  Everything is materialised on the fly
into ``configs/_llff_sweep/`` (so you can still ``scripts/eval_ckpt.py``
each run afterwards).

The sweep is designed to be *safe on 24 GB*: we keep ``cap_max=250k``
(the fern setting that ran reliably) and use the same 7000 iters /
scene. Total cost per scene ≈ 5-10 min for DAv2, ≈ 3-5 min for baseline.

Usage
-----
    python scripts/run_llff_sweep.py                # all 8 scenes, both variants
    python scripts/run_llff_sweep.py --scenes flower horns trex
    python scripts/run_llff_sweep.py --only dav2s   # skip baselines
    python scripts/run_llff_sweep.py --dry-run      # just emit configs

Run with ``--resume`` (default) to skip runs whose ``metrics.json``
already exists — safe to rerun after a crash.
"""
from __future__ import annotations

import argparse
import os
import subprocess
import sys
import time
from pathlib import Path
from typing import List, Optional

# Bootstrap
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from scripts import _bootstrap  # noqa: E402,F401

_ROOT = _bootstrap.PROJECT_ROOT
_CFG_OUT = _ROOT / "configs" / "_llff_sweep"
_OUT_ROOT = _ROOT / "outputs"

LLFF_SCENES = ["fern", "flower", "fortress", "horns",
               "leaves", "orchids", "room", "trex"]

# Per-scene overrides.
#
# fern/flower/fortress/horns have already been trained at cap_max=250k in a
# clean, just-booted CUDA context. For the remaining scenes we saw:
#   - leaves  baseline (150k): OK
#   - leaves  dav2s    (250k): OOM @ step 807 (15 GB alloc)
#   - orchids baseline (250k): OOM @ step 912 (15.44 GB alloc)
# The default-strategy densify kernel sometimes tries to allocate
# O(N^2 / something) intermediate buffers on high-grad scenes. Cap at 180k
# to leave >5 GB headroom on a 24 GB card.
_SCENE_OVERRIDES = {
    "leaves":  {"cap_max": 150000},
    "orchids": {"cap_max": 180000},
    "room":    {"cap_max": 180000},
    "trex":    {"cap_max": 180000},
}


# ---------------------------------------------------------------------
# config templates (mirror configs/llff_fern_n3_{baseline,dav2s}.yaml)
# ---------------------------------------------------------------------
_BASELINE_TMPL = """_base_: ../base.yaml

# Auto-generated by scripts/run_llff_sweep.py. Mirrors
# configs/llff_fern_n3_baseline.yaml with only ``scene`` swapped.

experiment:
  name: llff_{scene}_n3_baseline

data:
  type: llff
  root: data/nerf_llff_data
  scene: {scene}
  n_train_views: 3
  train_view_ids: null
  image_downsample: 4
  white_background: false
  recenter: true
  rescale: true
  sparse_mode: uniform

model:
  sh_degree: 3
  init:
    type: random_in_box
    num_points: 200000
    extent: 4.0
    rgb_init: 0.5
  scale_init_factor: 0.02

renderer:
  near_plane: 0.01
  far_plane: 1.0e10
  rasterize_mode: antialiased
  packed: false
  absgrad: true
  render_mode: RGB+ED

strategy:
  cap_max: 250000
  grow_grad2d: 0.00025
  refine_stop_iter: 6000

train:
  iterations: 7000
  ssim_lambda: 0.2

ssl:
  multiview_photo: {{enabled: false, weight: 0.0}}
  depth_consist:   {{enabled: false, weight: 0.0}}
  ema_teacher:     {{enabled: false, weight: 0.0}}
  pseudo_view:     {{enabled: false, weight: 0.0}}
  feature:         {{enabled: false, weight: 0.0}}

eval:
  render_test_at_end: true
  num_test_renders: null
  lpips: true
  lpips_net: vgg
"""

_DAV2S_TMPL = """_base_: ../base.yaml

# Auto-generated by scripts/run_llff_sweep.py. Mirrors
# configs/llff_fern_n3_dav2s.yaml with only ``scene`` swapped.

experiment:
  name: llff_{scene}_n3_dav2s

data:
  type: llff
  root: data/nerf_llff_data
  scene: {scene}
  n_train_views: 3
  train_view_ids: null
  image_downsample: 4
  white_background: false
  recenter: true
  rescale: true
  sparse_mode: uniform
  depth_prior:
    enabled: true
    backend: cache
    tag: depth_anything_v2_small_hf
    kind: disparity
    required: false

model:
  sh_degree: 3
  init:
    type: random_in_box
    num_points: 200000
    extent: 4.0
    rgb_init: 0.5
  scale_init_factor: 0.02

renderer:
  near_plane: 0.01
  far_plane: 1.0e10
  rasterize_mode: antialiased
  packed: false
  absgrad: true
  render_mode: RGB+ED

strategy:
  cap_max: 250000
  grow_grad2d: 0.00025
  refine_stop_iter: 6000

train:
  iterations: 7000
  ssim_lambda: 0.2

ssl:
  multiview_photo:
    enabled: true
    weight: 0.10
    start_iter: 1500
    n_neighbors: 1
    alpha_thresh: 0.0
    ssim_lambda: 0.0
    depth_eps: 0.001
    occlusion_check: true
    occlusion_start_iter: 3000
    occlusion_tau: 0.10
    occlusion_alpha_thresh: 0.0

  depth_consist:
    enabled: true
    weight: 0.05
    start_iter: 500
    alpha_thresh: 0.0
    space: disparity
    depth_eps: 0.001

  ema_teacher:     {{enabled: false, weight: 0.0}}
  pseudo_view:     {{enabled: false, weight: 0.0}}
  feature:         {{enabled: false, weight: 0.0}}

eval:
  render_test_at_end: true
  num_test_renders: null
  lpips: true
  lpips_net: vgg
"""


def _emit_config(scene: str, variant: str) -> Path:
    _CFG_OUT.mkdir(parents=True, exist_ok=True)
    tmpl = _BASELINE_TMPL if variant == "baseline" else _DAV2S_TMPL
    body = tmpl.format(scene=scene)

    # Apply per-scene overrides (currently just cap_max for leaves).
    ov = _SCENE_OVERRIDES.get(scene)
    if ov and "cap_max" in ov:
        # The default body has ``cap_max: 250000`` — rewrite it.
        body = body.replace("cap_max: 250000", f"cap_max: {ov['cap_max']}")

    path = _CFG_OUT / f"llff_{scene}_n3_{variant}.yaml"
    with open(path, "w", encoding="utf-8") as f:
        f.write(body)
    return path


def _run_already_done(scene: str, variant: str) -> bool:
    d = _OUT_ROOT / f"llff_{scene}_n3_{variant}"
    m = d / "metrics.json"
    return m.is_file()


def _train(cfg_path: Path, log_path: Path) -> int:
    """Invoke ``scripts/train.py`` as a subprocess. Returns exit code.

    The child is spawned with ``CREATE_NO_WINDOW`` on Windows so it never
    pops a console (previously each child opened a cmd window that, when
    closed by the user, killed the whole process group via a CLOSE event).
    We also set ``PYTORCH_ALLOC_CONF=expandable_segments:True`` to reduce
    the chance of fragmentation-OOM on 24 GB.
    """
    py = sys.executable
    cmd = [py, str(_ROOT / "scripts" / "train.py"),
           "--config", str(cfg_path)]
    log_path.parent.mkdir(parents=True, exist_ok=True)
    print(f"  [train] {' '.join(cmd)}  > {log_path}", flush=True)

    # Windows: hide console completely.
    creationflags = 0
    if os.name == "nt":
        CREATE_NO_WINDOW = 0x08000000
        creationflags = CREATE_NO_WINDOW

    env = os.environ.copy()
    # Help PyTorch avoid big fragmented reservations.
    env.setdefault("PYTORCH_ALLOC_CONF", "expandable_segments:True")
    # Legacy name (for older PyTorch) — harmless to set both.
    env.setdefault("PYTORCH_CUDA_ALLOC_CONF", "expandable_segments:True")

    t0 = time.time()
    with open(log_path, "w", encoding="utf-8") as f:
        rc = subprocess.call(
            cmd,
            stdout=f,
            stderr=subprocess.STDOUT,
            stdin=subprocess.DEVNULL,
            cwd=str(_ROOT),
            creationflags=creationflags,
            env=env,
        )
    dt = time.time() - t0
    print(f"  [train] exit={rc}  elapsed={dt:.1f}s", flush=True)
    return rc


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--scenes", nargs="+", default=LLFF_SCENES,
                    help=f"subset of scenes; default = all 8 {LLFF_SCENES}")
    ap.add_argument("--only", choices=["baseline", "dav2s", "both"],
                    default="both")
    ap.add_argument("--dry-run", action="store_true",
                    help="emit configs but don't train")
    ap.add_argument("--no-resume", action="store_true",
                    help="overwrite runs whose metrics.json already exists")
    args = ap.parse_args()

    variants: List[str] = {"baseline": ["baseline"], "dav2s": ["dav2s"],
                           "both": ["baseline", "dav2s"]}[args.only]

    # Emit configs first (this is cheap; helpful for auditing).
    emitted: List[tuple[str, str, Path]] = []
    for scene in args.scenes:
        if scene not in LLFF_SCENES:
            print(f"[warn] unknown scene {scene!r}; skipping")
            continue
        for v in variants:
            p = _emit_config(scene, v)
            emitted.append((scene, v, p))

    print(f"[sweep] emitted {len(emitted)} configs under {_CFG_OUT}")
    for scene, v, p in emitted:
        tag = "[done]" if _run_already_done(scene, v) else "[todo]"
        print(f"  {tag}  {scene:10s}  {v:10s}  -> {p.name}")

    if args.dry_run:
        print("[sweep] --dry-run; exiting without training")
        return

    # Train.
    log_dir = _OUT_ROOT / "_llff_sweep_logs"
    log_dir.mkdir(parents=True, exist_ok=True)
    n_skip, n_ok, n_fail = 0, 0, 0
    fails: List[tuple[str, str, int]] = []
    t_sweep = time.time()
    for scene, v, cfg in emitted:
        run_name = f"llff_{scene}_n3_{v}"
        if not args.no_resume and _run_already_done(scene, v):
            print(f"[skip] {run_name} (metrics.json exists)")
            n_skip += 1
            continue
        print(f"\n[run] {run_name}")
        rc = _train(cfg, log_dir / f"{run_name}.log")
        if rc == 0 and _run_already_done(scene, v):
            n_ok += 1
        else:
            n_fail += 1
            fails.append((scene, v, rc))

    dt = time.time() - t_sweep
    print(f"\n[sweep] total elapsed {dt/60:.1f} min  "
          f"ok={n_ok} skip={n_skip} fail={n_fail}")
    if fails:
        print("[sweep] failures:")
        for s, v, rc in fails:
            print(f"  {s}/{v}: rc={rc}   "
                  f"see {log_dir / f'llff_{s}_n3_{v}.log'}")


if __name__ == "__main__":
    main()
